server:
  port:
    1111

spring:
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:sqlite:bike.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
#
#jdbc:
#  driver: org.sqlite.JDBC