server:
  port:
    1111

spring:
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:sqlite:bike.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC

auth0:
  issuer: https://aereliz.eu.auth0.com/
# api/v2/
  apiAudience: http://localhost:1111
#
#jdbc:
#  driver: org.sqlite.JDBC